// First Plus — admin
// Classic script: execution order preserved from the original HTML.


const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',students:'<path d="m3 9 9-5 9 5-9 5-9-5zM6 11v6q6 5 12 0v-6M21 9v7"/>',teachers:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-5a6 6 0 0 1 12 0v5M16 4h5v12h-4"/>',attendance:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 11h18m-14 5 3 3 5-5"/>',payments:'<rect x="2" y="5" width="20" height="15" rx="2"/><path d="M2 10h20M6 15h4"/>',admissions:'<path d="M14 3H5v18h14V8l-5-5v5h5M8 13h8M8 17h5"/>',announcements:'<path d="m3 10 15-5v14L3 14v-4zm3 5 2 6h3l-2-5M21 9v6"/>',reports:'<path d="M4 3v18h17M8 16v-5M13 16V7M18 16v-8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',bell:'<path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3zM10 21h4"/>',plus:'<path d="M12 5v14M5 12h14"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',arrow:'<path d="m14 7-5 5 5 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};
const icon=n=>`<svg class="ico" viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.dashboard}</svg>`;
const crest=`<img class="emblem" src="../assets/images/image-01.png" alt="شعار مدارس فيرست بلس الخاصة">`;
const labels={dashboard:'لوحة المعلومات',students:'إدارة الطلاب',teachers:'هيئة التدريس',attendance:'الحضور والغياب',payments:'المدفوعات',admissions:'طلبات القبول',announcements:'الإعلانات',reports:'التقارير',settings:'الإعدادات'};
document.getElementById('brand').innerHTML=crest+'<span><b>فيرست بلس</b><small>FIRST PLUS SCHOOL</small></span>';
document.getElementById('nav').innerHTML=Object.entries(labels).map(([k,v])=>`<button data-page="${k}" onclick="go('${k}')">${icon(k)}${v}</button>`).join('');document.getElementById('searchIcon').innerHTML=icon('search');document.getElementById('notificationBtn').innerHTML=icon('bell')+'<span class="dot"></span>';
const ar=n=>new Intl.NumberFormat('ar-EG').format(n);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let students=[{id:1001,name:'أحمد محمد علي',stage:'ابتدائي',grade:'الخامس / أ',parent:'محمد علي',status:'نشط'},{id:1002,name:'مريم أحمد حسن',stage:'ابتدائي',grade:'الثاني / ب',parent:'أحمد حسن',status:'نشط'},{id:1003,name:'عمر خالد محمود',stage:'إعدادي',grade:'الأول / أ',parent:'خالد محمود',status:'نشط'},{id:1004,name:'فريدة محمود سامي',stage:'رياض الأطفال',grade:'KG2 / أ',parent:'محمود سامي',status:'نشط'},{id:1005,name:'يوسف أحمد عادل',stage:'ثانوي',grade:'الأول / أ',parent:'أحمد عادل',status:'نشط'},{id:1006,name:'ليلى حسن إبراهيم',stage:'ابتدائي',grade:'الثالث / ب',parent:'حسن إبراهيم',status:'نشط'},{id:1007,name:'سليم عمرو محمد',stage:'إعدادي',grade:'الثاني / ب',parent:'عمرو محمد',status:'نشط'},{id:1008,name:'ملك كريم حسن',stage:'رياض الأطفال',grade:'KG1 / أ',parent:'كريم حسن',status:'نشط'}];
let payments=[{id:1,name:'أحمد محمد علي',amount:3000,date:'2026-09-28'},{id:2,name:'مريم أحمد حسن',amount:2500,date:'2026-09-27'},{id:3,name:'عمر خالد محمود',amount:3000,date:'2026-09-26'}];let applications=[{id:1,name:'آدم مصطفى أحمد',stage:'رياض الأطفال',status:'قيد المراجعة'},{id:2,name:'نور علي محمود',stage:'ابتدائي',status:'قيد المراجعة'},{id:3,name:'حسن محمد عمرو',stage:'إعدادي',status:'قيد المراجعة'}];let announcements=[{title:'اجتماع هيئة التدريس',audience:'المدرسون',text:'اجتماع تجريبي لمناقشة خطة الأنشطة للفصل الدراسي الأول.'}];let attendance=Object.fromEntries(students.map((s,i)=>[s.id,i===2?'غائب':'حاضر']));let activities=[['تسجيل سداد قسط دراسي','المالية · سجل تجريبي'],['استلام طلب التحاق جديد','القبول · سجل تجريبي'],['تحديث سجل حضور اليوم','شؤون الطلاب · سجل تجريبي']];let query='',stageFilter='',page='dashboard',lastFocus;const today='2026-09-28';
const button=(t,fn,cls='')=>`<button class="btn ${cls}" onclick="${fn}">${t}</button>`;const tag=(t,c='')=>`<span class="pill ${c}">${esc(t)}</span>`;const card=(title,body,action='')=>`<section class="card"><div class="card-head"><h2>${title}</h2>${action}</div><div class="card-body">${body}</div></section>`;
const table=(headers,rows)=>`<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="empty">لا توجد نتائج مطابقة.</td></tr>`}</tbody></table></div>`;
function stat(label,value,ic,foot){return `<div class="card stat"><div class="stat-top">${label}<span class="stat-icon">${icon(ic)}</span></div><strong>${value}</strong><div class="stat-foot">${foot}</div></div>`}
function studentRows(list,compact=false){return list.map(s=>`<tr><td><div class="student-name"><span class="initial">${esc(s.name.charAt(0))}</span><div>${esc(s.name)}<small class="muted" style="display:block;font-size:10px">FPS-${s.id}</small></div></div></td><td>${esc(s.stage)}</td><td>${esc(s.grade)}</td><td>${tag(s.status,'green')}</td><td><button class="linkbtn" onclick="studentDetail(${s.id})">عرض الملف ←</button>${compact?'':`<button class="linkbtn" onclick="studentForm(${s.id})">تعديل</button>`}</td></tr>`)}
function dashboard(){let present=students.filter(s=>attendance[s.id]==='حاضر').length,total=payments.reduce((a,b)=>a+b.amount,0);return `<section class="welcome"><div><small style="color:#dbb66a">مكتب المدير / بداية يوم جديد</small><h2>أهلًا بك، مدير المدرسة</h2><p>كل ما تحتاجه لمتابعة مدرستك في مكان واحد.<br>إليك ملخص الطلاب والحضور وآخر المستجدات.</p></div>${crest}<i class="spark" style="left:25%"></i><i class="spark" style="left:44%;animation-delay:2s"></i><i class="spark" style="left:70%;animation-delay:4s"></i></section><div class="stats">${stat('إجمالي الطلاب',ar(students.length),'students','طلاب السجل التجريبي')}${stat('هيئة التدريس',ar(4),'teachers','معلمون في هذه المعاينة')}${stat('الحضور اليوم',ar(Math.round(present/students.length*100))+'٪','attendance',ar(present)+' حاضر من '+ar(students.length)+' طلاب')}${stat('المدفوعات المسجلة',ar(total)+' <small>ج.م</small>','payments',ar(payments.length)+' عمليات سداد تجريبية')}</div><div class="columns">${card('الحضور خلال الأسبوع',`<div class="chart">${[88,100,88,75,88].map(x=>`<div class="chart-col"><b>${ar(x)}٪</b><div class="chart-bar" style="height:${x*.9}%"></div></div>`).join('')}</div><div class="chart-labels">${['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس'].map(x=>`<span>${x}</span>`).join('')}</div><div class="chart-note"><i></i>نسب تاريخية توضيحية مستقلة عن سجل اليوم</div>`,`<span class="pill">أسبوع توضيحي</span>`)}${distribution()}</div><div style="margin-bottom:23px">${card('إجراءات سريعة',`<div class="quick"><button onclick="studentForm()">${icon('plus')}إضافة طالب</button><button onclick="go('attendance')">${icon('attendance')}تسجيل الحضور</button><button onclick="announcementForm()">${icon('announcements')}إعلان جديد</button><button onclick="paymentForm()">${icon('payments')}تسجيل دفعة</button></div>`)}</div><div class="columns"><section class="card"><div class="card-head" style="padding-bottom:20px"><h2>أحدث الطلاب</h2><button class="linkbtn" onclick="go('students')">عرض الكل ←</button></div>${table(['الطالب','المرحلة','الفصل','الحالة',''],studentRows(students.slice(-4).reverse(),true))}</section>${card('تنبيهات ومتابعات',`<div class="alerts"><div class="activity"><span class="stat-icon">${icon('admissions')}</span><div><b>${ar(applications.filter(a=>a.status==='قيد المراجعة').length)} طلبات قبول تنتظر المراجعة</b><small>راجع بيانات المتقدمين وحدد القرار.</small></div><button class="linkbtn" onclick="go('admissions')">عرض</button></div><div class="activity"><span class="stat-icon">${icon('attendance')}</span><div><b>${ar(students.filter(s=>attendance[s.id]==='غائب').length)} حالات غياب اليوم</b><small>متابعة سجل حضور الطلاب.</small></div><button class="linkbtn" onclick="go('attendance')">عرض</button></div></div>` )}</div>${card('آخر الأنشطة',activities.slice(0,4).map(([a,b])=>`<div class="activity"><span class="stat-icon">${icon('clock')}</span><div>${esc(a)}<small>${esc(b)}</small></div></div>`).join(''))}`}
function distribution(){const colors=['#71171e','#c99a41','#e2c989','#eee6d3'],ss=['رياض الأطفال','ابتدائي','إعدادي','ثانوي'];let cum=0;const segments=ss.map((t,i)=>{let n=students.filter(s=>s.stage===t).length,start=cum;cum+=n/students.length*100;return `${colors[i]} ${start}% ${cum}%`});return card('توزيع الطلاب',`<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${segments.join(',')})"><div><b>${ar(students.length)}</b><small>إجمالي الطلاب</small></div></div><div class="legend">${ss.map((t,i)=>`<div><i style="background:${colors[i]}"></i>${t}<b>${ar(students.filter(s=>s.stage===t).length)}</b></div>`).join('')}</div></div><div class="chart-note">التوزيع حسب المرحلة التعليمية</div>`)}
function studentsPage(){return `<div class="card"><div class="toolbar"><input id="studentQuery" placeholder="بحث بالاسم أو رقم الطالب…" aria-label="بحث الطلاب" value="${esc(query)}" oninput="query=this.value;filterStudents()"><select aria-label="المرحلة" onchange="stageFilter=this.value;filterStudents()"><option value="">كل المراحل</option>${['رياض الأطفال','ابتدائي','إعدادي','ثانوي'].map(s=>`<option ${s===stageFilter?'selected':''}>${s}</option>`).join('')}</select>${button(icon('download')+'تصدير CSV',"exportStudents()")}</div><div id="studentTable"></div><div style="padding:15px 20px;font-size:12px;color:#947b55" id="resultCount"></div></div>`}
function filterStudents(){const list=students.filter(s=>(s.name.includes(query)||String(s.id).includes(query))&&(!stageFilter||s.stage===stageFilter));document.getElementById('studentTable').innerHTML=table(['الطالب','المرحلة','الفصل','الحالة','الإجراءات'],studentRows(list));document.getElementById('resultCount').textContent=ar(list.length)+' طالب من أصل '+ar(students.length)}
function attendancePage(){return `<div class="banner">${icon('attendance')}سجل اليوم التوضيحي: ٢٨ سبتمبر ٢٠٢٦. التغييرات تبقى في هذه الجلسة فقط.</div><section class="card">${table(['الطالب','الفصل','الحضور'],students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.grade)}</td><td><select class="select" aria-label="حضور ${esc(s.name)}" data-attendance="${s.id}">${['حاضر','غائب','متأخر'].map(t=>`<option ${attendance[s.id]===t?'selected':''}>${t}</option>`).join('')}</select></td></tr>`))}<div class="toolbar">${button('حفظ سجل الحضور',"saveAttendance()",'primary')}</div></section>`}
function paymentsPage(){return `<div class="stats">${stat('إجمالي المسجل',ar(payments.reduce((a,b)=>a+b.amount,0))+' ج.م','payments','مدفوعات نموذجية فقط')}${stat('عدد العمليات',ar(payments.length),'reports','دون ربط ببوابة دفع')}</div><section class="card">${table(['رقم العملية','الطالب','المبلغ','التاريخ'],payments.slice().reverse().map(p=>`<tr><td>PAY-${p.id}</td><td>${esc(p.name)}</td><td>${ar(p.amount)} ج.م</td><td>${esc(p.date)}</td></tr>`))}</section>`}
function admissionsPage(){return `<div class="banner">القبول والرفض هنا يغيّران حالة الطلب التجريبي فقط، ولا يرسلان رسائل ولا ينشئان حساب طالب.</div><section class="card">${table(['المتقدم','المرحلة','الحالة','القرار'],applications.map(a=>`<tr><td>${esc(a.name)}</td><td>${a.stage}</td><td>${tag(a.status,a.status==='مقبول'?'green':a.status==='مرفوض'?'red':'')}</td><td>${a.status==='قيد المراجعة'?button('مراجعة',`reviewApplication(${a.id})`):button('إعادة للمراجعة',`applicationStatus(${a.id},'قيد المراجعة')`)}</td></tr>`))}</section>`}
function teachersPage(){return `<div class="card">${table(['المعلم','التخصص','الفصول','الحالة'],[['محمد عبد الرحمن','الرياضيات','الخامس / أ، الثالث / ب'],['سارة أحمد','اللغة العربية','الثاني / ب'],['أحمد محمود','العلوم','الأول الإعدادي / أ'],['منى علي','رياض الأطفال','KG1 / أ، KG2 / أ']].map(([n,s,g])=>`<tr><td>${n}</td><td>${s}</td><td>${g}</td><td>${tag('على رأس العمل','green')}</td></tr>`))}</div><p class="muted" style="margin-top:15px;font-size:13px">سجل تعريفي تجريبي للعرض فقط؛ تحرير ملفات المعلمين يأتي في المرحلة التالية.</p>`}
function announcementsPage(){return announcements.map(a=>card(esc(a.title),`<span class="pill">${esc(a.audience)}</span><p style="margin-top:15px">${esc(a.text)}</p><small class="muted">إعلان تجريبي، لم يُرسل إلى أي مستخدم.</small>`)).join('<br>')}
function reportsPage(){return `<div class="columns">${distribution()}${card('تصدير السجلات',`<p class="muted" style="font-size:14px;margin-bottom:20px">تنزيل بيانات الجلسة الحالية بصيغة CSV المتوافقة مع برامج الجداول.</p><div class="quick"><button onclick="exportStudents()">${icon('download')}قائمة الطلاب</button><button onclick="exportAttendance()">${icon('download')}حضور اليوم</button><button onclick="exportPayments()">${icon('download')}المدفوعات</button></div>`)}</div>`}
function settingsPage(){return card('إعدادات النسخة التجريبية','<p class="muted">هذه النسخة لا تحتوي على خادم أو تسجيل دخول أو صلاحيات فعلية. كل البيانات في ذاكرة الصفحة وتعود للأمثلة الأصلية عند إعادة تحميلها. لا تُدخل بيانات حقيقية للطلاب.</p><div class="banner" style="margin-top:20px">الهوية البصرية: الأحمر الداكن والذهبي · الخطوط مضمنة داخل الملف · دعم الشاشات الصغيرة وتقليل الحركة.</div>'+button('إعادة ضبط البيانات التجريبية',"resetDemo()"))}
function render(){page=location.hash.slice(1)||'dashboard';if(!labels[page])page='dashboard';document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false')});const title=labels[page];let action=page==='students'?button(icon('plus')+'إضافة طالب',"studentForm()",'primary'):page==='payments'?button(icon('plus')+'تسجيل دفعة',"paymentForm()",'primary'):page==='announcements'?button(icon('plus')+'إعلان جديد',"announcementForm()",'primary'):page==='dashboard'?button(icon('plus')+'إضافة طالب',"studentForm()",'primary'):'';const views={dashboard,students:studentsPage,teachers:teachersPage,attendance:attendancePage,payments:paymentsPage,admissions:admissionsPage,announcements:announcementsPage,reports:reportsPage,settings:settingsPage};document.getElementById('main').innerHTML=`<div class="reveal"><div class="bread">مكتب المدير / ${title}</div><div class="heading"><div><h1>${title}</h1><p>${page==='dashboard'?'نظرة شاملة على يومك الدراسي، بكل وضوح.':'إدارة منظّمة، ومتابعة أقرب لكل التفاصيل.'}</p></div>${action}</div><div class="banner">${icon('settings')}بيانات تجريبية • التعديلات مؤقتة لهذه الجلسة وتُمسح عند إعادة تحميل الصفحة.</div>${views[page]()}<footer class="foot"><span>© ٢٠٢٦ مدرسة فيرست بلس الخاصة</span><span>FIRST PLUS · نبني العقول، ونصنع المستقبل</span></footer></div>`;if(page==='students')filterStudents();toggleMenu(false)}
function go(p){if(location.hash==='#'+p)render();else location.hash=p}
function toggleMenu(open){let s=document.getElementById('sidebar'),v=typeof open==='boolean'?open:!s.classList.contains('open');s.classList.toggle('open',v);document.getElementById('overlay').classList.toggle('open',v);document.getElementById('menuButton').setAttribute('aria-expanded',v)}
let toastTimer;function toast(t){let e=document.getElementById('toast');e.textContent=t;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,4500)}
function modal(title,html){lastFocus=document.activeElement;document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modalBack').hidden=false;document.body.style.overflow='hidden';document.querySelector('#modalBody input,#modalBody button,#modalBack button').focus()}
function closeModal(){document.getElementById('modalBack').hidden=true;document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus()}
const field=(l,n,v='',type='text')=>`<label class="field">${l} *<input name="${n}" type="${type}" value="${esc(v)}" required maxlength="100"></label>`;
function studentForm(id){let s=students.find(s=>s.id===id)||{name:'',parent:'',stage:'ابتدائي',grade:''};modal(id?'تعديل بيانات الطالب':'إضافة طالب تجريبي',`<form id="studentForm"><div class="form-grid">${field('اسم الطالب','name',s.name)}${field('ولي الأمر','parent',s.parent)}<label class="field">المرحلة *<select name="stage">${['رياض الأطفال','ابتدائي','إعدادي','ثانوي'].map(t=>`<option ${s.stage===t?'selected':''}>${t}</option>`).join('')}</select></label>${field('الصف / الفصل','grade',s.grade)}</div><p class="muted" style="font-size:12px;margin-top:15px">استخدم بيانات وهمية فقط. الحفظ داخل الجلسة وليس في قاعدة بيانات.</p><div class="form-actions"><button class="btn primary" type="submit">حفظ الطالب</button><button class="btn" type="button" onclick="closeModal()">إلغاء</button></div></form>`);document.getElementById('studentForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),o=Object.fromEntries(f);for(let [k,v]of Object.entries(o))o[k]=v.trim();if(Object.values(o).some(v=>!v)){toast('يرجى استكمال الحقول دون مسافات فارغة.');return}if(id)Object.assign(s,o);else{let id2=Math.max(...students.map(s=>s.id))+1;students.push({...o,id:id2,status:'نشط'});attendance[id2]='حاضر'}activities.unshift([id?'تعديل بيانات طالب':'إضافة طالب تجريبي','شؤون الطلاب · الآن']);closeModal();render();toast('تم حفظ الطالب داخل الجلسة التجريبية.')}}
function studentDetail(id){const s=students.find(s=>s.id===id);modal('ملف الطالب',`<h2 style="color:var(--wine)">${esc(s.name)}</h2><p class="muted">FPS-${s.id} · ${esc(s.stage)} · ${esc(s.grade)}</p><div class="banner" style="margin-top:20px">ولي الأمر: ${esc(s.parent)}</div><p>حضور اليوم: ${tag(attendance[id]||'غير مسجل')}</p><p style="margin:15px 0">المدفوعات المسجلة: <b>${ar(payments.filter(p=>p.name===s.name).reduce((a,p)=>a+p.amount,0))} ج.م</b></p><small class="muted">الدرجات والسلوك والمستندات ليست ضمن هذه الدفعة.</small>`)}
function saveAttendance(){document.querySelectorAll('[data-attendance]').forEach(s=>attendance[s.dataset.attendance]=s.value);activities.unshift(['تحديث سجل حضور اليوم','شؤون الطلاب · الآن']);toast('تم حفظ سجل الحضور في الجلسة الحالية.');render()}
function paymentForm(){modal('تسجيل دفعة تجريبية',`<form id="paymentForm"><div class="form-grid"><label class="field full">الطالب *<select name="student">${students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label class="field">المبلغ بالجنيه *<input type="number" min="1" max="1000000" step="0.01" name="amount" required></label>${field('تاريخ السداد','date',today,'date')}</div><div class="banner" style="margin-top:20px">تسجيل محاسبي تجريبي فقط، لا يتم تحصيل أموال أو إصدار إيصال رسمي.</div><button class="btn primary" type="submit">تسجيل الدفعة</button></form>`);document.getElementById('paymentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);payments.push({id:payments.length+1,name:students.find(s=>s.id===Number(f.get('student'))).name,amount:Number(f.get('amount')),date:f.get('date')});activities.unshift(['تسجيل دفعة تجريبية جديدة','المالية · الآن']);closeModal();render();toast('تم تسجيل الدفعة التجريبية.') }}
function reviewApplication(id){const a=applications.find(a=>a.id===id);modal('مراجعة طلب القبول',`<h2>${esc(a.name)}</h2><p class="muted">المرحلة المطلوبة: ${a.stage}</p><div class="banner" style="margin-top:20px">بيانات مختصرة تجريبية. القرار يحدّث الحالة فقط؛ المستندات والمقابلات غير مرفقة.</div><div class="form-actions">${button('قبول الطلب',`applicationStatus(${id},'مقبول')`,'primary')}${button('رفض الطلب',`applicationStatus(${id},'مرفوض')`)}</div>`)}
function applicationStatus(id,status){applications.find(a=>a.id===id).status=status;closeModal();activities.unshift(['تغيير حالة طلب قبول إلى '+status,'القبول · الآن']);render();toast('تم تحديث الحالة التجريبية.')}
function announcementForm(){modal('إنشاء إعلان تجريبي',`<form id="announcementForm"><div class="form-grid">${field('عنوان الإعلان','title')}<label class="field">الجمهور<select name="audience"><option>الجميع</option><option>المدرسون</option><option>أولياء الأمور</option></select></label><label class="field full">نص الإعلان *<textarea name="text" rows="4" maxlength="1500" required></textarea></label></div><div class="banner" style="margin-top:18px">يُضاف الإعلان إلى هذه المعاينة فقط؛ لن يرسل إشعارات أو رسائل.</div><button class="btn primary">حفظ الإعلان</button></form>`);document.getElementById('announcementForm').onsubmit=e=>{e.preventDefault();let a=Object.fromEntries(new FormData(e.target));if(!a.title.trim()||!a.text.trim()){toast('يرجى كتابة عنوان ونص الإعلان.');return}announcements.unshift(a);activities.unshift(['إنشاء إعلان جديد','الإدارة · الآن']);closeModal();go('announcements');toast('تم حفظ الإعلان التجريبي.')}}
function notifications(){modal('إشعارات المتابعة',`<div class="activity">${icon('admissions')}<div>${ar(applications.filter(a=>a.status==='قيد المراجعة').length)} طلبات قبول تنتظر المراجعة.<br><button class="linkbtn" onclick="closeModal();go('admissions')">مراجعة الطلبات ←</button></div></div><div class="activity">${icon('attendance')}<div>${ar(students.filter(s=>attendance[s.id]==='غائب').length)} حالات غياب اليوم.<br><button class="linkbtn" onclick="closeModal();go('attendance')">فتح سجل الحضور ←</button></div></div><p class="muted" style="font-size:12px;margin-top:15px">إشعارات مشتقة من البيانات التجريبية الحالية، وليست إشعارات مباشرة من خادم.</p>`)}
function csv(name,rows){const safe=v=>{let t=String(v);if(/^[=+@\-\t\r]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};let blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('تم تجهيز ملف CSV. إذا منعت المعاينة التنزيل، افتح ملف HTML في متصفحك.')}
function exportStudents(){csv('first-plus-students.csv',[['رقم الطالب','الاسم','المرحلة','الفصل','ولي الأمر','الحالة'],...students.filter(s=>page!=='students'||((s.name.includes(query)||String(s.id).includes(query))&&(!stageFilter||s.stage===stageFilter))).map(s=>[s.id,s.name,s.stage,s.grade,s.parent,s.status])])}
function exportAttendance(){csv('first-plus-attendance.csv',[['الطالب','الفصل','الحضور','التاريخ'],...students.map(s=>[s.name,s.grade,attendance[s.id],today])])}
function exportPayments(){csv('first-plus-payments.csv',[['العملية','الطالب','المبلغ','التاريخ'],...payments.map(p=>[p.id,p.name,p.amount,p.date])])}
function resetDemo(){modal('إعادة ضبط المعاينة','<p>ستفقد كل الإضافات والتعديلات في الجلسة الحالية وتعود البيانات الأصلية.</p><div class="form-actions">'+button('إعادة الضبط',"location.reload()",'primary')+button('إلغاء',"closeModal()")+'</div>')}
document.getElementById('globalSearch').onsubmit=e=>{e.preventDefault();query=document.getElementById('globalQuery').value.trim();stageFilter='';go('students')};document.getElementById('modalBack').addEventListener('click',e=>{if(e.target.id==='modalBack')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();toggleMenu(false)}if(e.key==='Tab'&&!document.getElementById('modalBack').hidden){let nodes=[...document.querySelectorAll('#modalBack button,#modalBack input,#modalBack select,#modalBack textarea,#modalBack a[href]')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
